### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by rtcms** [Balasys/dheater#4]
Either way I run
Install it via pip or use it via Docker I get the following error

```
┌──(kali㉿kali)-[~]
└─$ docker run --tty --rm balasys/dheater --protocol tls domainwhichiownandreachable.com                                                    1 ⨯
Traceback (most recent call last):
  File "/usr/local/bin/dheat", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/dheater/__main__.py", line 331, in main
    enforcer = DHEnforcerThreadTLS(args.uri, args.timeout, pre_check_result)
  File "<attrs generated init dheater.__main__.DHEnforcerThreadBase>", line 15, in __init__
  File "/usr/local/lib/python3.9/site-packages/dheater/__main__.py", line 100, in __attrs_post_init__
    self._pre_check()
  File "/usr/local/lib/python3.9/site-packages/dheater/__main__.py", line 264, in _pre_check
    server_messages = self._get_client().do_tls_handshake(
  File "/usr/local/lib/python3.9/site-packages/cryptolyzer/tls/client.py", line 429, in do_tls_handshake
    return self._do_handshake(
  File "/usr/local/lib/python3.9/site-packages/cryptolyzer/tls/client.py", line 409, in _do_handshake
    l7_client.do_handshake(self, hello_message, record_version, last_handshake_message_type)
  File "/usr/local/lib/python3.9/site-packages/cryptolyzer/tls/client.py", line 1181, in do_handshake
    self._process_non_handshake_message(record.content_type, message)
  File "/usr/local/lib/python3.9/site-packages/cryptolyzer/tls/client.py", line 1135, in _process_non_handshake_message
    raise TlsAlert(message.description)
cryptolyzer.tls.exception.TlsAlert: TlsAlert(description=<TlsAlertDescription.HANDSHAKE_FAILURE: 40>)
```

**Comment by c0r0n3r** [comment]
Could you provide version information?

- pip show dheater
- docker images balasys/dheater

It seems to me that you do not use the latest version.

**Comment by rtcms** [comment]
Here you go
```
┌──(kali㉿kali)-[~]
└─$ pip show dheater                                                                                                  1 ⨯

Name: DHEater
Version: 0.2.3
Summary: D(HE)ater is an attacking tool heating the CPU by enforcing DHE KEX in case of TLS and SSH
Home-page: https://github.com/balasys/dheater
Author: BalaSys IT Security
Author-email: 
License: Apache-2.0
Location: /home/kali/.local/lib/python3.9/site-packages
Requires: attrs, cryptolyzer, cryptoparser, urllib3
Required-by:
```



```
┌──(kali㉿kali)-[~]
└─$ docker images balasys/dheater                                                                                     1 ⨯

REPOSITORY        TAG       IMAGE ID       CREATED      SIZE
balasys/dheater   latest    a16f9c3b4c11   8 days ago   137MB

```

**Comment by c0r0n3r** [comment]
Meanwhile 0.2.4 has been released. I hope your issue has already been fixed in this version. Could you test it please?

**Comment by c0r0n3r** [comment]
@rtcms please reopen if the issue still exists in the latest version.
